# Generated by CodiumAI
from modeling.config import GPTConfig


class TestGPTConfig:

    #  Create a GPTConfig object with default parameters.
    def test_create_default_parameters(self):
        config = GPTConfig(vocab_size=10000, max_len=512)
        assert config.vocab_size == 10000
        assert config.max_len == 512
        assert config.num_heads == 12
        assert config.num_blocks == 12
        assert config.embed_dim == 768
        assert config.attn_dropout == 0.1
        assert config.embed_dropout == 0.1
        assert config.feed_forward_dropout == 0.1

    #  Create a GPTConfig object with custom parameters.
    def test_create_custom_parameters(self):
        config = GPTConfig(vocab_size=20000, max_len=1024, num_heads=8, num_blocks=8, embed_dim=512, attn_dropout=0.2,
                           embed_dropout=0.2, feed_forward_dropout=0.2)
        assert config.vocab_size == 20000
        assert config.max_len == 1024
        assert config.num_heads == 8
        assert config.num_blocks == 8
        assert config.embed_dim == 512
        assert config.attn_dropout == 0.2
        assert config.embed_dropout == 0.2
        assert config.feed_forward_dropout == 0.2
